routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/admin', function () {
    return view('welcome');
});*/

//Admin Routes
  //Admin Display Images
    //Route::get('/adminPanel', 'pagesController\PagesController@getAdminPanel');
  Route::prefix('admin')->group(function(){
    Route::get('/login', 'Auth\AdminLoginController@showLoginPage')->name('adminlogin');
    Route::post('/adminlogin', 'Auth\AdminLoginController@login')->name('adminactionlogin');
    Route::get('/home', 'admin\AdminController@index')->name('adminhome');
    Route::resource('/admin', 'admin\adminRegistration');
    Route::get('/logout', 'Auth\AdminLoginController@logoutAdmin')->name('logoutadmin');
    Route::get('/verify', 'admin\adminRegistration@showVerify')->name('verify.admin.email');
    Route::get('/verify/{email}/{verify_token}', 'admin\adminRegistration@sendEmailDone')->name('sendEmailAdminDone');
    //department
    Route::get('/department', 'admin\adminDepartmentController@display')->name('department.view');
    Route::get('/department/create', 'admin\adminDepartmentController@create')->name('department.create');
    Route::get('/department/update', 'admin\adminDepartmentController@update')->name('department.update');
    //yearlevel
    Route::get('/yearlevel', 'admin\adminYearLevelController@display')->name('yearlevel.view');
    Route::get('/yearlevel/create', 'admin\adminYearLevelController@create')->name('yearlevel.create');
    //sections
    Route::get('/sections', 'admin\adminSectionController@display')->name('sections.view');
    Route::get('/sections/create', 'admin\adminSectionController@create')->name('sections.create');
    //subjects
    Route::get('/subjects', 'admin\adminSubjectsController@display')->name('subjects.view');
    Route::get('/subjects/create', 'admin\adminSubjectsController@create')->name('subjects.create');

  });
  Route::get('/home', function(){
    return view('error', ['error'=>'Not found']);
  })->name('errorhome');

Auth::routes();

resources/views/AdminView/_adminStylesheet.blade.php
 <!-- Bootstrap -->
    <link href="{{asset('css/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('fonts/font-awesome.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('css/nprogress.css')}}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{asset('css/green.css')}}" rel="stylesheet">
	
    <!-- bootstrap-progressbar -->
    <link href="{{asset('css/bootstrap-progressbar-3.3.4.min.css')}}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{{asset('css/jqvmap.min.css')}}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{{asset('css/daterangepicker.css')}}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{asset('css/custom.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/generic.css')}}" rel="stylesheet">

resources/views/AdminView/adminAccountValidationTemplate.blade.php
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>@yield('title')</title>
		<link href="{{asset('bootstrap4/css/bootstrap.min.css')}}" rel="stylesheet">
		<link href="{{asset('css/generic.css')}}" rel="stylesheet">
    @yield('css')
	</head>
	<body>
    @yield('content')
		<script src= '{{asset('bootstrap4/js/jquery.js')}}'></script>
		<script src= '{{asset('js/parsley.min.js')}}'></script>
		<script src= '{{asset('bootstrap4/js/tether.min.js')}}'></script>
		<script src= '{{asset('bootstrap4/js/bootstrap.min.js')}}'></script>
		@yield('scripts')
	</body>
</html>

resources/views/AdminView/adminEmail.blade.php
To verify your email please click
<a href = "{{route('sendEmailAdminDone', ['email'=>$user->email, 'verify_token'=>$user->verify_token])}}">here</a>

resources/views/AdminView/adminHome.blade.php
@extends('AdminView.adminTemplate')

@section('title', 'AdminDashboard')
@section('stylesheet')
	<link href="{{asset('css/admin/adminHome.css')}}" rel="stylesheet">
@stop
@section('content')
  <h1>
    Hello world!
  </h1>

  @if(Auth::guard('admin')->check())
    you are loggin as an admin

  @endif
@endSection

resources/views/AdminView/adminLogin.blade.php
	@extends('AdminView.adminAccountValidationTemplate')
	@section('title', 'Admin Registration')
	@section('css')
		<link href="{{asset('css/admin/adminLogin.css')}}" rel="stylesheet">
	@stop
	@section('content')
		<div id = 'flexContainer' >

			<div id ='regAdminForm'>
				@include('Partials._message')
				<div><center><strong>Admin-Login</strong></center></div>


					{!! Form::open(['route' => 'adminactionlogin',
									'data-parsley-validate'=>'']) !!}
						{{Form:: label('email', 'Email:')}}
						{{Form:: text('email', null, array(
															'placeholder'=>'Username',
															'class'=>'form-control',
															'required'=>'',
															'maxlength'=>'100'))}}
						{{Form:: label('password', 'Password:')}}
						{{Form:: password('password', array(
															'placeholder'=>'Password',
															'class'=>'form-control',
															'required'=>'',
															'maxlength'=>'100'))}}
						<div class='genericDivTop'>

						{{Form::checkbox('remember_me')}}
						{{Form:: label('remember_me', 'Remember me')}}
						</div>
						{{Form::submit('Login', array('class'=>'btn btn-success btn-block'))}}
						{!! Form::close() !!}
						<div>
							<div class='row'>
								<div class='col-6'>
									{{Html::link('#', 'Forgot Password', array('class'=>'btn btn-block btn-info genericDivTop'

																														))}}
								</div>
								<div class='col-6'>
									<a href ='{{route('admin.create')}}' class='btn btn-block btn-primary genericDivTop'>Register</a>
								</div>
							</div>
						</div>


		</div>
	</div>
@stop

resources/views/AdminView/adminRegistration.blade.php
@extends('AdminView.adminAccountValidationTemplate')
		@section('title', 'Admin Registration')
		@section('css')
		<link href="{{asset('css/admin/adminRegistration.css')}}" rel="stylesheet">
		@stop
		@section('content')
		<div id = 'flexContainer' >

			<div id ='regAdminForm'>
				@include('Partials._message')
				{!! Form::open(['route' => 'admin.store',
								'data-parsley-validate'=>'',
								'files'=>true]) !!}
					<div>
						<center>
							<img src="{{asset('images/defaultimage.png')}}" id = 'profileImage' class="genericImageCircle" alt="Cinque Terre">
						</center>
					</div>
					<div>
					{{Form::label('uploadProfileImage', 'Upload Profile Picture:')}}
					{{Form::file('uploadProfileImage', array('accept'=>
						'.png,.jpg'
					))}}
				</div>
					{{Form:: label('userName', 'Username:')}}
					{{Form:: text('userName', null, array(
														'placeholder'=>'Username',
														'class'=>'form-control',
														'required'=>'',
														'maxlength'=>'100'))}}
					{{Form:: label('password', 'Password:')}}
					{{Form:: password('password', array(
														'placeholder'=>'Password',
														'class'=>'form-control',
														'required'=>'',
														'maxlength'=>'100',
														'data-parsley-equalto'=>"#password_confirmation"))}}
					{{Form:: label('password_confirmation', 'Confirm Password:')}}
					{{Form:: password('password_confirmation', array(
														'placeholder'=>'Confirm Password',
														'class'=>'form-control',
														'required'=>'',
														'maxlength'=>'100',
														'data-parsley-equalto'=>"#password"))}}
					{{Form:: label('adminKey', 'Admin Key:')}}
					{{Form:: password('adminKey', array(
														'placeholder'=>'Confirm Password',
														'class'=>'form-control',
														'required'=>'',
														'maxlength'=>'100'))}}
					{{Form:: label('email', 'Email:')}}
					{{Form:: email('email', null, array(
														'placeholder'=>'Email',
														'class'=>'form-control',
														'required'=>'',
														'maxlength'=>'100',
														'data-parsley-type='=>"email"))}}

					{{Form::submit('Register Admin', array('class'=>'btn btn-success btn-block',
															'style'=>'margin-top:20px;'))}}
				{!! Form::close() !!}
				
			</div>
		</div>
	@stop
	@section('scripts')
		<script src= '{{asset('js/admin/adminRegistration.js')}}'></script>
	@stop

resources/views/AdminView/adminSuccessRegistration.blade.php
@extends('AdminView.adminAccountValidationTemplate')
@section('title', 'Admin Registration')

@section('css')
<link href="{{asset('css/admin/adminSuccessRegistration.css')}}" rel="stylesheet">
@stop
@section('content')
		<div id = 'flexContainer' >
			<div id ='regAdminForm'>
				@include('Partials._message')
				<div id = 'adminInfo'>
					<div class='genericDivBottom'>
						<strong>Username:</strong>
					</div>
					<div class='genericDivBottom'>
						<strong>email:</strong>
					</div>
					<div  class='genericDivBottom'>
						{{$userName}}
					</div>
					<div  class='genericDivBottom'>
						{{$email}}
					</div>
				</div>
				<div>
					<a class='btn btn-success' href = "{{route('adminlogin')}}">Go to login page</a>
					
				</div>
			</div>
		</div>
@stop

resources/views/AdminView/adminTemplate.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    @include('Partials._metaHead')

    @include('Partials.AdminPartials._adminStylesheet')
    @yield('stylesheet')
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Hello Admin!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{asset('images-database/admin/'.Auth::guard('admin')->id().'.'.session()->get('admin')['imageType'])}}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{session()->get('admin')['userName']}}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            @include('Partials.AdminPartials._sideBarAdmin')
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{route('logoutadmin')}}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{{asset('images-database/admin/'.Auth::guard('admin')->id().'.'.session()->get('admin')['imageType'])}}" alt="">{{session()->get('admin')['userName']}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="{{route('logoutadmin')}}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          @yield('content')
        </div>
        @include('Partials._footer')
        </div>
    </div>
      <!-- jQuery -->
    @include('Partials.AdminPartials._adminScripts')
    @yield('scripts')
  </body>
</html>

resources/views/AdminView/verifyEmail.blade.php
@extends('AdminView.adminAccountValidationTemplate')
@section('title', 'Admin Verification')

@section('css')
<link href="{{asset('css/admin/adminVerify.css')}}" rel="stylesheet">
@stop
@section('content')
		<div id = 'flexContainer' >
			<div id ='regAdminForm'>
				@include('Partials._message')
				<div id = 'adminInfo'>
					<strong>Please verify your account by clicking the link we sent to your email.</strong>
				</div>
			</div>
		</div>
@stop